### ISSUE TITLE
background.jpg -> source available?

### ISSUE THREAD

**Issue by austrianAudioJV** [sudara/pamplejuce#114]
Hi @sudara ,

Would it be possible to add the source file for the "background.jpg" resource to the repo, perhaps as an SVG file?  This would be beneficial in that it would provide a template for the background.jpg - and, especially if it were in .svg format (source), would enable an additional feature: auto-generating the background.jpg/background@2x.jpg files at build time.

If you add the .svg (hopefully its .svg?), I'll shortly thereafter add a PR that generates the necessary binary resources from it.

**Comment by sudara** [comment]
Howdy!!

The source is Figma, but it's also out of date, as the Standalone was added since then. Best thing to do is just roll without a background, or screenshot the dmg and pull it into photoshop or something if you want to add arrows, etc...

I'm going to close this one, as the next step is to move away from .dmg and use .pkg files which are much more universally supported across macos versions. See #46 for more on that...
